name: 'VRChat Data Tracker'
description: 'WIP action for tracking data from the VRChat API'
branding:
  icon: globe
  color: blue
inputs:
  workspace:
    description: 'The workspace directory.'
    default: '/github/workspace'
  directory:
    description: 'The root directory to upload from (relative to workspace). Example, "path/to/build/artifacts".'
    required: true
  username:
    description: 'VRChat Username'
    required: true
  password:
    description: 'VRChat Password'
    required: true
  group:
    description: 'VRChat Group ID to track'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '-w'
  - ${{ inputs.workspace }}
  - '-d'
  - ${{ inputs.directory }}
  - '-u'
  - ${{ inputs.username }}
  - '-p'
  - ${{ inputs.password }}
  - '-g'
  - ${{ inputs.group }}